version: '3.9'

services:
  app:
    container_name: fsf-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/fsf
      APP_JWT_SECRET: changeme-super-secret
      NEXTAUTH_URL: http://localhost:3000
      SQUARE_PRICE_CENTS: "2000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run build &&
        npm start
      "

  db:
    container_name: fsf-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fsf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

#version: "3.9"
#services:
#  db:
#    image: postgres:16-alpine
#    environment:
#      POSTGRES_DB: fsf
#      POSTGRES_USER: fsf
#      POSTGRES_PASSWORD: fsf
#    volumes:
#      - dbdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

#  web:
#    build: .
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgres://mnf:mnf@db:5432/mnf
#      APP_JWT_SECRET: change-me
#      NEXTAUTH_URL: http://localhost:3000
#      SQUARE_PRICE_CENTS: 2000
#    ports:
#      - "3000:3000"

#volumes:
#  dbdata:
