services:
  - type: web
    name: fsf
    env: node
    plan: basic-256

    buildCommand: |
      echo "DATABASE_URL=$DATABASE_URL" > .env
      npm ci
      npx prisma generate
      npm run build

    startCommand: |
      npx prisma migrate deploy
      npm start

    envVars:
      - key: DATABASE_URL
        #fromDatabase: mnf-db
        fromDatabase: t11sports-db
        name: postgres

      - key: APP_JWT_SECRET
        generateValue: true

      - key: NEXTAUTH_URL
        value: https://your-render-url.onrender.com

      - key: SQUARE_PRICE_CENTS
        value: "2000"

databases:
  - name: fsf
    plan: basic-256
