services:
  - type: web
    name: fsf
    env: node
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    plan: basic-256
    envVars:
      - key: DATABASE_URL
        fromDatabase: mnf-db
        name: postgres
      - key: APP_JWT_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://your-render-url.onrender.com
      - key: SQUARE_PRICE_CENTS
        value: "2000"
databases:
  - name: fsf
    plan: basic-256
